version: "3.8"

services:
  cleanup:
    image: servivum/docker-host-cleanup:19.03
    environment:
      CRON_INTERVAL: '0 3 * * *'
      # PRUNE_BUILD_CACHES: 'true'
      # PRUNE_CONTAINERS: 'true'
      PRUNE_IMAGES: 'true'
      # PRUNE_IMAGES_ALL: 'true'
      # PRUNE_NETWORKS: 'true'
      # PRUNE_VOLUMES: 'true'
      # PRUNE_SYSTEM: 'true'
    deploy:
      mode: global
    stop_grace_period: 1s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
