version: "3.8"

services:
  cleanup:
    build:
      context: .
      dockerfile: 19.03/Dockerfile
    environment:
      CRON_INTERVAL: '* * * * *'
      PRUNE_BUILD_CACHES: 'false'
      PRUNE_CONTAINERS: 'false'
      #PRUNE_IMAGES: 'true'
      #PRUNE_IMAGES_ALL: 'true'
      PRUNE_NETWORKS: 'false'
      PRUNE_VOLUMES: 'false'
      PRUNE_SYSTEM: 'false'
    stop_grace_period: 1s
    volumes:
      - "./etc/cron/crontab-template:/etc/cron/crontab-template"
      - "./usr/local/bin/cleanup.sh:/usr/local/bin/cleanup.sh"
      - "./usr/local/bin/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
      - "/var/run/docker.sock:/var/run/docker.sock"